#!/bin/sh
scriptnames="$@"
MATLABCMD="2025b"
WALLTIME=01:30:00
MEM=8gb

module purge
module load matlab/${MATLABCMD}

for mfile in ${scriptnames}
do
sbatch -t $WALLTIME --mem=$MEM --wrap="matlab -nojvm -nodisplay -nodesktop < ${mfile}"
sleep .05
done
